@startuml
"Client"->"ChecklistController":addChecklist(ChecklistDto checklistDto)
"ChecklistController"->"ChecklistService":addChecklist(Checklist checklist)
database DB
"ChecklistService"->DB:query
@enduml