@startuml DelegationReport
Client->DelegationService:downloadReport(Long delegationId)
DelegationService->DelegationRepository:getDelegationByDelegationId(Long delegationId)
database db
DelegationRepository->db:query
db-->DelegationRepository:entity
DelegationRepository-->DelegationService:Delegation delegation
DelegationService-->ExpenseRepository:getExpensesByDelegationId(Long delegationId)
database db
ExpenseRepository->db:query
db-->ExpenseRepository:entity
ExpenseRepository-->DelegationService:Iterable<Expense> expenses
DelegationService-->Client:ReportDto
@enduml