@startuml PobierzListeDelegacji
"Client"->"DelegationService":getDelegations(String, userLogin, LocalDateTime since, LocalDateTime until, DelegationStatus status)
alt filtering by status
    "DelegationService"->DelegationRepository:getDelegations(DelegationStatus status)
    database DB
    DelegationRepository->DB:query
    DB-->DelegationRepository:result
    DelegationRepository-->"DelegationService":Iterable<Delegation> delegations
else filtering by date
    "DelegationService"->DelegationRepository:getDelegations(LocalDateTime since, LocalDateTime until)
    DelegationRepository->DB:query
    DB-->DelegationRepository:result
    DelegationRepository-->"DelegationService":Iterable<Delegation> delegations
else flitering by user
    "DelegationService"->DelegationRepository:getDelegations(DelegationStatus status)
    DelegationRepository->DB:query
    DB-->DelegationRepository:result
    DelegationRepository-->"DelegationService":Iterable<Delegation> delegations
else flitering by all parameters
    "DelegationService"->DelegationRepository:getDelegations(String userLogin, DelegationStatus status, LocalDateTime since, LocalDateTime until)
    DelegationRepository->DB:query
    DB-->DelegationRepository:result
    DelegationRepository-->"DelegationService":Iterable<Delegation> delegations
else without filtering - all delegations
    "DelegationService"->DelegationRepository:getDelegations()
    DelegationRepository->DB:query
    DB-->DelegationRepository:result
    DelegationRepository-->"DelegationService":Iterable<Delegation> delegations
end
"DelegationService"-->Client:Iterable<DelegationDTO> delegationDtos
@enduml