@startuml
ExpenseSettingsPage->ExpenseSettingsPage: fetchExchangeRates()
Client-->ExpenseSettingsPage: tap button to change default rate
ExpenseSettingsPage->ExpenseService: saveDefaultExchangeRate({rate})
database db
ExpenseService->db: saveUserDefaultExchangeRate({rate})
db-->ExpenseService: return status
ExpenseService-->ExpenseSettingsPage: return status
ExpenseSettingsPage-->Client: return status
@enduml