@startuml
Client->DelegationService:{Post} saveDelegation()
DelegationService->DelegationRepository:saveDelegation()
database db
DelegationRepository->db:query
db-->DelegationRepository:entities
DelegationRepository-->DelegationService:Delegation
DelegationService-->Client:DelegationDTO
@enduml
